arm64/dts: fix VtsFirmwareDtboVerification fails
ERROR: ufdt_verify_fragment():failed to verify fragment[fragment@50], overlay node __overlay__ to target l1-icache
After fixed above usb_otg overlay issue, it fails again because below error
ERROR: ufdt_verify_fragment():failed to verify fragment[fragment@7], overlay node __overlay__ to target soc
fix gpio_key pin ctrl overlay issue

Change-Id: I5f33d8a37bfbc9c86686b69590d235029aa38e3f
Reviewed-on: https://gerrit.mot.com/1302517
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Xiangpo Zhao <zhaoxp3@motorola.com>
Submit-Approved: Jira Key